apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: velagapudisirisha/budget-app-db:latest
        ports:
        - containerPort: 5432
        env:
          - name: POSTGRES_DB
            value: Ruby_database
          - name: POSTGRES_USER
            value: Sirisha
          - name: POSTGRES_PASSWORD
            value: password
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: postgres-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
