# Use the official PostgreSQL image from Docker Hub
FROM postgres:latest

# Optional: Set environment variables (customize as needed)
ENV POSTGRES_USER=Sirisha \
    POSTGRES_PASSWORD=password \
    POSTGRES_DB=Ruby_database

# Optional: Add initialization scripts
# COPY init.sql /docker-entrypoint-initdb.d/
 #COPY init.sh /docker-entrypoint-initdb.d/
# Use the official PostgreSQL image with the tag

# Copy custom initialization scripts
COPY init-user-db.sh /docker-entrypoint-initdb.d/

# Expose the PostgreSQL port
#EXPOSE 5432

# Optional: Grant execute permission to the scripts
 #RUN chmod +x /docker-entrypoint-initdb.d/init.sh

# Optional: Expose PostgreSQL port (default: 5432)
 EXPOSE 5432

